### ISSUE TITLE
Relation names are used for model types.

### ISSUE THREAD

**Issue by ralfschimmel** [scoutforpets/jsonapi-mapper#30]
First of all; great work 👍 

However; I noticed that relation names are used as model types.
For example; I have a model with two `belongsTo`'s called `goodGuy` and `badGuy` of the type `guy`. The mapper returns JSON with related data as expected, though the type of the models is `goodGuys` and `badGuys` instead of `guys` for both.

**Comment by jamesdixon** [comment]
Hi, @ralfschimmel. Thanks 😄 

I haven't run into this myself as all of my types map directly to the model. That said, it's a perfectly valid case. I believe that our code doesn't support this at the moment, but it certainly could be added to the roadmap. The potential issue, which we've faced previously, is that we're highly dependent on the information Bookshelf gives us in order to be able to map the model properly. That said, I'm not sure if information about a base type, such as `guys` is available in the model. Any chance you might be able to investigate to see if you can find this in the model before it's passed to the mapper? If so, then this would probably be a relatively trivial change to implement.

Cheers,
James

**Comment by chamini2** [comment]
I did the investigation and from my findings, it's not in the bookshelf model. I propose to check an attribute in the bookshelf model (maybe `._modelName`) and if it's present use that name, if it's not present use the relation name.

**Comment by ShadowManu** [comment]
I highly discourage adding non-public (expected) properties to objects to work as a public API. Even less when the object is foreign (coming from the `bookshelf` package).We could instead play with the mapper instance options or the map method options.

**Comment by jamesdixon** [comment]
Agreed -- if this is going to be supported, it should probably be something that's passed to the mapper as an option.

@ralfschimmel did you end up finding a solution to this problem? Curious if it's something we could implement.

**Comment by confuser** [comment]
Just came across this issue myself. @jamesdixon What about using a virtual property to support this, such as `type` or `_type`?

**Comment by ShadowManu** [comment]
@confuser what do you think on extending the `relations` option to accept an object working as a map for name conversions? I think that is approachable and flexible.

**Comment by confuser** [comment]
Sounds like a viable solution. It does mean additional setup for each serialisation, rather than a behind the scene meta approach, but it would be the more flexible option.

**Comment by ShadowManu** [comment]
Since its a customization about the mapping/serialization process, I personally think its better to treat it in here than to delegate it to customizations on the bookshelf side.

**Comment by ShadowManu** [comment]
@confuser This functionality has been added as as new Mapper option, which you can see how it works [here in the specs](https://github.com/scoutforpets/jsonapi-mapper/blob/refactor/spec/bookshelf-spec.ts#L1373). I believe this covers the use case?

**Comment by chamini2** [comment]
Fixed in d0c43e0fa0f7bcb7d3b546796e09d8057e9ea0cb , check the [README](https://github.com/scoutforpets/jsonapi-mapper#api)  and [specs](https://github.com/scoutforpets/jsonapi-mapper/blob/b4136ccf1a32e588887950d9ca153bb163b6465a/spec/bookshelf-spec.ts#L1448) [(and here)](https://github.com/scoutforpets/jsonapi-mapper/blob/b4136ccf1a32e588887950d9ca153bb163b6465a/spec/bookshelf-spec.ts#L1477) for the usage instructions.
